In [43]:
import requests
import pandas as pd
from datetime import date
from bs4 import BeautifulSoup

In [7]:
pd.date_range(start = '2020-02-07', end = date.today(), freq = 'D')

DatetimeIndex(['2020-02-07', '2020-02-08', '2020-02-09', '2020-02-10',
               '2020-02-11', '2020-02-12', '2020-02-13', '2020-02-14',
               '2020-02-15', '2020-02-16',
               ...
               '2020-10-12', '2020-10-13', '2020-10-14', '2020-10-15',
               '2020-10-16', '2020-10-17', '2020-10-18', '2020-10-19',
               '2020-10-20', '2020-10-21'],
              dtype='datetime64[ns]', length=258, freq='D')

In [10]:
df = pd.DataFrame(
    {'date': pd.date_range(start = '2020-02-07', end = date.today(), freq = 'D')}
)
df

          date
0   2020-02-07
1   2020-02-08
2   2020-02-09
3   2020-02-10
4   2020-02-11
..         ...
253 2020-10-17
254 2020-10-18
255 2020-10-19
256 2020-10-20
257 2020-10-21

[258 rows x 1 columns]

In [22]:
df['url_short'] = 'moh' + df['date'].dt.strftime('%-d%b').str.lower()
df

          date url_short
0   2020-02-07   moh7feb
1   2020-02-08   moh8feb
2   2020-02-09   moh9feb
3   2020-02-10  moh10feb
4   2020-02-11  moh11feb
..         ...       ...
253 2020-10-17  moh17oct
254 2020-10-18  moh18oct
255 2020-10-19  moh19oct
256 2020-10-20  moh20oct
257 2020-10-21  moh21oct

[258 rows x 2 columns]

In [23]:
df['url_short_ext'] = 'https://go.gov.sg/' + df['url_short']
df

          date url_short               url_short_ext
0   2020-02-07   moh7feb   https://go.gov.sg/moh7feb
1   2020-02-08   moh8feb   https://go.gov.sg/moh8feb
2   2020-02-09   moh9feb   https://go.gov.sg/moh9feb
3   2020-02-10  moh10feb  https://go.gov.sg/moh10feb
4   2020-02-11  moh11feb  https://go.gov.sg/moh11feb
..         ...       ...                         ...
253 2020-10-17  moh17oct  https://go.gov.sg/moh17oct
254 2020-10-18  moh18oct  https://go.gov.sg/moh18oct
255 2020-10-19  moh19oct  https://go.gov.sg/moh19oct
256 2020-10-20  moh20oct  https://go.gov.sg/moh20oct
257 2020-10-21  moh21oct  https://go.gov.sg/moh21oct

[258 rows x 3 columns]

In [50]:
def get_long_url(url_short):
    url_long = ''
    header = {
        'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64; rv:77.0) Gecko/20100101 Firefox/77.0'
    }
    
    response = requests.get(url_short, headers = header)
    
    if(response.status_code == 200):
        content = response.content if response.status_code == 200 else ''
        soup = BeautifulSoup(content, 'html.parser')
        url_long = soup.find('p').get('data-href')
    
    return url_long

get_long_url('https://go.gov.sg/moh24apr')

'https://www.moh.gov.sg/news-highlights/details/38-more-cases-discharged-897-new-cases-of-covid-19-infection-confirmed'

In [54]:
df['url_long'] = df['url_short_ext'].apply(lambda url: get_long_url(url))
df

,date,url_short,url_short_ext,url_long
0,2020-02-07,moh7feb,https://go.gov.sg/moh7feb,https://www.moh.gov.sg/news-highlights/details...
1,2020-02-08,moh8feb,https://go.gov.sg/moh8feb,https://www.moh.gov.sg/news-highlights/details...
2,2020-02-09,moh9feb,https://go.gov.sg/moh9feb,https://www.moh.gov.sg/news-highlights/details...
3,2020-02-10,moh10feb,https://go.gov.sg/moh10feb,https://www.moh.gov.sg/news-highlights/details...
4,2020-02-11,moh11feb,https://go.gov.sg/moh11feb,https://www.moh.gov.sg/news-highlights/details...
...,...,...,...,...
253,2020-10-17,moh17oct,https://go.gov.sg/moh17oct,https://www.moh.gov.sg/news-highlights/details...
254,2020-10-18,moh18oct,https://go.gov.sg/moh18oct,https://www.moh.gov.sg/news-highlights/details...
255,2020-10-19,moh19oct,https://go.gov.sg/moh19oct,https://www.moh.gov.sg/news-highlights/details...
256,2020-10-20,moh20oct,https://go.gov.sg/moh20oct,https://www.moh.gov.sg/news-highlights/details...
257,2020-10-21,moh21oct,https://go.gov.sg/moh21oct,

In [55]:
df.to_csv('out/urls.csv')